wandb_version: 1

Model:
  desc: null
  value: dqn_new
Env:
  desc: null
  value: TiagoSimpleEnv-v0
Batch size:
  desc: null
  value: 64
lr:
  desc: null
  value: 1e-4
seed:
  desc: null
  value: 42
FL Flower:
  desc: null
  value: true
Sample Clients:
  desc: null
  value: 1
Total Clients:
  desc: null
  value: 1
FL Rounds:
  desc: null
  value: 5
Iterations per FL Round:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    python_version: 3.10.6
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708939608.038173
    t:
      1:
      - 1
      - 2
      - 3
      - 30
      - 41
      - 55
      3:
      - 13
      - 15
      - 16
      - 23
      4: 3.10.6
      5: 0.16.0
      8:
      - 5
      13: linux-x86_64
