save_dir: save/
device: cuda
seed: 42
model_name: 'ddpg'
discrete_actions: false

training_parameters:
  lr: 1e-4
  batch_size: 64
  hidden1: 128
  hidden2: 128  
  num_steps: 500
  train_steps: 1000
  gamma: 0.99 #discount
  tau: 0.9
  updating_freq: 10 

  # for exploration 
  eps_start: 1.0
  eps_end: 0.01
  eps_decay: 200000 #10000 #depsilon
  oup_theta: 0.01
  oup_mu: 0
  oup_sigma: 1.0
  oup_decay: 200000
  
  num_eval_episodes: 1
  training_step_evaluate: 500
  replay_buffer_size: 50000
  min_len_replay_buffer: 100 #00

fl_parameters:
  sample_clients: 1
  total_clients: 1
  num_rounds: 1
  iterations_per_fl_round: 1000