save_dir: save/
device: cuda
seed: 42
model_name: 'ddpg'
discrete_actions: false

training_parameters:
  lr: 1e-4
  batch_size: 64
  hidden1: 64
  hidden2: 128  
  num_steps: 500
  train_steps: 100000
  gamma: 0.90 #discount
  tau: 1.0
  policy_coef: 0.5
  value_coef: 1.0
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 10000 #depsilon
  num_eval_episodes: 1
  training_step_evaluate: 500
  replay_buffer_size: 10000
  min_len_replay_buffer: 1000

fl_parameters:
  sample_clients: 1
  total_clients: 1
  num_rounds: 5
  iterations_per_fl_round: 1