save_dir: save/
device: cuda
seed: 42
model_name: 'ddpg'
discrete_actions: false

training_parameters:
  lr: 1e-4
  batch_size: 64
  hidden1: 64
  hidden2: 128  
  num_steps: 500
  train_steps: 100
  gamma: 0.90 #discount
  tau: 0.9
  policy_coef: 0.5
  value_coef: 0.5

  # for exploration 
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 50000 #10000 #depsilon
  oup_theta: 0.05
  oup_mu: 0
  oup_sigma: 1.0
  oup_decay: 50000
  

  num_eval_episodes: 10
  training_step_evaluate: 500
  replay_buffer_size: 5000
  min_len_replay_buffer: 200 #0

fl_parameters:
  sample_clients: 1
  total_clients: 1
  num_rounds: 1 #5 #10
  iterations_per_fl_round: 1 #20