save_dir: save/
device: cuda
seed: 42
model_name: 'dqn'

# Cartpole
training_parameters:
  lr: 1e-4
  batch_size: 128
  num_steps: 10000
  gamma: 0.90
  tau: 1.0
  update_target_net: 1000
  eps_start: 1.0
  eps_end: 0.05
  eps_decay: 10000
  num_eval_episodes: 100
  training_step_evaluate: 2000
  replay_buffer_size: 500000
  min_len_replay_buffer: 1000

fl_parameters:
  sample_clients: 1
  total_clients: 1
  num_rounds: 10
  iterations_per_fl_round: 1