# TiagoSimpleEnv:
# - continue cartesian space actions
# - NO multimodal obs
# - actions as cartesian pos increments

env_name: 'TiagoSimpleEnv-v0'
input_dim: 39 
action_dim: 4
multimodal: false
velocity: 0.007
max_episode_steps: 100