# TiagoSimpleEnv:
# - joint space actions
# - NO multimodal obs
# - actions as joint velocities

env_name: 'TiagoSimpleEnv-v0'
input_dim: 28 #43 
action_dim: 8
multimodal: false
gz_speed: 0.005
random_init: False
max_episode_steps: 500