# TiagoSimpleEnv:
# - joint space actions
# - NO multimodal obs
# - actions as joint increments

env_name: 'TiagoSimpleEnv-v0'
input_dim: 43 
action_dim: 8
multimodal: false
gui: false
velocity: 0.007
max_episode_steps: 100